function initDb_v7(dbPath)
%INITDB_V7 Ensure SQLite DB exists and schema is created.
% Robust across MATLAB sqlite behaviors:
%   - Some versions: 'connect' requires file to exist
%   - Some versions: 'create' requires file to NOT exist
% We handle both via try/catch.

dbPath = char(string(dbPath));

% Ensure parent directory exists
dbDir = fileparts(dbPath);
if ~isempty(dbDir) && exist(dbDir,'dir') ~= 7
    mkdir(dbDir);
end

% Open connection robustly
conn = openSqliteRobust_(dbPath);

% Foreign keys on
exec(conn, 'PRAGMA foreign_keys = ON;');

% ---- bats
exec(conn, [ ...
'CREATE TABLE IF NOT EXISTS bats (' ...
'bat_id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
'bat_code TEXT NOT NULL UNIQUE' ...
');' ]);

% ---- trials
exec(conn, [ ...
'CREATE TABLE IF NOT EXISTS trials (' ...
'trial_id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
'bat_id INTEGER NOT NULL,' ...
'date TEXT,' ...
'trial TEXT,' ...
'condition TEXT,' ...
'catch_trial INTEGER,' ...
'temperature_C REAL,' ...
'humidity_pct REAL,' ...
'fs_hz REAL,' ...
'source_mat TEXT,' ...
'created_at TEXT DEFAULT CURRENT_TIMESTAMP,' ...
'UNIQUE(bat_id, date, trial, source_mat),' ...
'FOREIGN KEY(bat_id) REFERENCES bats(bat_id) ON DELETE CASCADE' ...
');' ]);

% ---- calls
exec(conn, [ ...
'CREATE TABLE IF NOT EXISTS calls (' ...
'call_id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
'trial_id INTEGER NOT NULL,' ...
'call_number INTEGER,' ...
'on_samp INTEGER,' ...
'off_samp INTEGER,' ...
'timestamp_s REAL,' ...
'duration_ms REAL,' ...
'ipi_ms REAL,' ...
'peakFreq_kHz REAL,' ...
'startFreq_kHz REAL,' ...
'endFreq_kHz REAL,' ...
'startFreq_low_kHz REAL,' ...
'startFreq_high_kHz REAL,' ...
'endFreq_ridge_kHz REAL,' ...
'endFreq_low_kHz REAL,' ...
'bandwidth_kHz REAL,' ...
'slope_kHz_per_ms REAL,' ...
'peakAmp_rear REAL,' ...
'peakAmp_left REAL,' ...
'peakAmp_right REAL,' ...
'FOREIGN KEY(trial_id) REFERENCES trials(trial_id) ON DELETE CASCADE,' ...
'UNIQUE(trial_id, call_number)' ...
');' ]);

close(conn);
end

% -------------------------
% Local helper
% -------------------------
function conn = openSqliteRobust_(dbPath)
% Try connect/create depending on existence and MATLAB behavior.

existsNow = (exist(dbPath,'file') == 2);

if existsNow
    % File exists: try connect first
    try
        conn = sqlite(dbPath,'connect');
        return;
    catch
        % Some builds might require 'connect' only; if connect fails even though file exists,
        % retry connect once more (rare) then error.
        conn = sqlite(dbPath,'connect');
        return;
    end
else
    % File does not exist: try create first
    try
        conn = sqlite(dbPath,'create');
        return;
    catch
        % Some builds only allow connect and will create implicitly; try connect
        conn = sqlite(dbPath,'connect');
        return;
    end
end
end
